
[JLL.products]
executable = ["gksqt", "grplot"]
library = ["libGKS", "libGR", "libGR3", "libGRM"]
[Status]
version = "0.73.21+0"

[Pkg]
is_jll = true
name = "GR_jll"
uuid = "d2c73de3-f751-5644-a686-071e5b155ba9"
