
[JLL.products]
library = ["libaws_c_io"]
[Status]
version = "0.24.0+0"

[[Issues."0.23.4+0"]]
version = "0.23.4+0"
type = "not_on_latest"
latest = "0.24.0+0"
dependent = ["aws_c_http_jll [3254fc65-9028-534d-aa9d-d76d128babc6]"]
dependency = []

[Pkg]
is_jll = true
name = "aws_c_io_jll"
uuid = "13c41daa-f319-5298-b5eb-5754e0170d52"
