[Pkg]
name = "aws_c_io_jll"
uuid = "13c41daa-f319-5298-b5eb-5754e0170d52"
is_jll = true

[Status]
version = "0.25.0+0"

[JLL.products]
library = ["libaws_c_io"]

[[Issues."0.25.0+0"]]
dependent = ["aws_c_http_jll [3254fc65-9028-534d-aa9d-d76d128babc6]"]
dependency = []
type = "not_on_latest"
version = "0.25.0+0"
latest = "0.26.0+0"
