[Status]
version = "1.6.0"

[[Issues."1.5.0"]]
version = "1.5.0"
type = "not_on_latest"
latest = "1.6.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqTsit5"
uuid = "b1df2697-797e-41e3-8120-5422d3b24e4a"
