[Pkg]
name = "FastPower"
uuid = "a4df4552-cc26-4903-aec0-212e50a0e84b"

[Status]
version = "1.3.0"

[[Issues."1.3.0"]]
type = "missing_deps"

    [[Issues."1.3.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
