[Pkg]
name = "ModelingToolkit"
uuid = "961ee093-0014-501f-94e3-6117800e7a78"

[Status]
version = "10.31.2"

[[Issues."11.2.0"]]
type = "missing_deps"

    [[Issues."11.2.0".deps]]
    name = "BipartiteGraphs"
    uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
    [[Issues."11.2.0".deps]]
    name = "ModelingToolkitBase"
    uuid = "7771a370-6774-4173-bd38-47e70ca0b839"
    [[Issues."11.2.0".deps]]
    name = "ModelingToolkitTearing"
    uuid = "6bb917b9-1269-42b9-9f7c-b0dca72083ab"
    [[Issues."11.2.0".deps]]
    name = "StateSelection"
    uuid = "64909d44-ed92-46a8-bbd9-f047dfbdc84b"

    [[Issues."11.2.0".weak_deps]]
    name = "FMI"
    uuid = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"

[[Issues."10.31.2"]]
type = "missing_deps"

    [[Issues."10.31.2".weak_deps]]
    name = "BifurcationKit"
    uuid = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
    [[Issues."10.31.2".weak_deps]]
    name = "CasADi"
    uuid = "c49709b8-5c63-11e9-2fb2-69db5844192f"
    [[Issues."10.31.2".weak_deps]]
    name = "FMI"
    uuid = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"
    [[Issues."10.31.2".weak_deps]]
    name = "InfiniteOpt"
    uuid = "20393b10-9daf-11e9-18c9-8db751c92c57"
    [[Issues."10.31.2".weak_deps]]
    name = "Pyomo"
    uuid = "0e8e1daf-01b5-4eba-a626-3897743a3816"

[[Issues."11.4.0"]]
type = "missing_deps"

    [[Issues."11.4.0".deps]]
    name = "BipartiteGraphs"
    uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
    [[Issues."11.4.0".deps]]
    name = "ModelingToolkitBase"
    uuid = "7771a370-6774-4173-bd38-47e70ca0b839"
    [[Issues."11.4.0".deps]]
    name = "ModelingToolkitTearing"
    uuid = "6bb917b9-1269-42b9-9f7c-b0dca72083ab"
    [[Issues."11.4.0".deps]]
    name = "StateSelection"
    uuid = "64909d44-ed92-46a8-bbd9-f047dfbdc84b"

    [[Issues."11.4.0".weak_deps]]
    name = "FMI"
    uuid = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"

[[Issues."11.5.1"]]
type = "missing_deps"

    [[Issues."11.5.1".deps]]
    name = "BipartiteGraphs"
    uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
    [[Issues."11.5.1".deps]]
    name = "ModelingToolkitBase"
    uuid = "7771a370-6774-4173-bd38-47e70ca0b839"
    [[Issues."11.5.1".deps]]
    name = "ModelingToolkitTearing"
    uuid = "6bb917b9-1269-42b9-9f7c-b0dca72083ab"
    [[Issues."11.5.1".deps]]
    name = "StateSelection"
    uuid = "64909d44-ed92-46a8-bbd9-f047dfbdc84b"

    [[Issues."11.5.1".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.5.0"]]
type = "missing_deps"

    [[Issues."11.5.0".deps]]
    name = "BipartiteGraphs"
    uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
    [[Issues."11.5.0".deps]]
    name = "ModelingToolkitBase"
    uuid = "7771a370-6774-4173-bd38-47e70ca0b839"
    [[Issues."11.5.0".deps]]
    name = "ModelingToolkitTearing"
    uuid = "6bb917b9-1269-42b9-9f7c-b0dca72083ab"
    [[Issues."11.5.0".deps]]
    name = "StateSelection"
    uuid = "64909d44-ed92-46a8-bbd9-f047dfbdc84b"

    [[Issues."11.5.0".weak_deps]]
    name = "FMIImport"
    uuid = "9fcbc62e-52a0-44e9-a616-1359a0008194"

[[Issues."11.1.0"]]
type = "missing_deps"

    [[Issues."11.1.0".deps]]
    name = "BipartiteGraphs"
    uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
    [[Issues."11.1.0".deps]]
    name = "ModelingToolkitBase"
    uuid = "7771a370-6774-4173-bd38-47e70ca0b839"
    [[Issues."11.1.0".deps]]
    name = "ModelingToolkitTearing"
    uuid = "6bb917b9-1269-42b9-9f7c-b0dca72083ab"
    [[Issues."11.1.0".deps]]
    name = "StateSelection"
    uuid = "64909d44-ed92-46a8-bbd9-f047dfbdc84b"

    [[Issues."11.1.0".weak_deps]]
    name = "FMI"
    uuid = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"

[[Issues."11.3.0"]]
type = "missing_deps"

    [[Issues."11.3.0".deps]]
    name = "BipartiteGraphs"
    uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
    [[Issues."11.3.0".deps]]
    name = "ModelingToolkitBase"
    uuid = "7771a370-6774-4173-bd38-47e70ca0b839"
    [[Issues."11.3.0".deps]]
    name = "ModelingToolkitTearing"
    uuid = "6bb917b9-1269-42b9-9f7c-b0dca72083ab"
    [[Issues."11.3.0".deps]]
    name = "StateSelection"
    uuid = "64909d44-ed92-46a8-bbd9-f047dfbdc84b"

    [[Issues."11.3.0".weak_deps]]
    name = "FMI"
    uuid = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"

[[Issues."11.0.0"]]
type = "missing_deps"

    [[Issues."11.0.0".deps]]
    name = "BipartiteGraphs"
    uuid = "caf10ac8-0290-4205-88aa-f15908547e8d"
    [[Issues."11.0.0".deps]]
    name = "ModelingToolkitBase"
    uuid = "7771a370-6774-4173-bd38-47e70ca0b839"
    [[Issues."11.0.0".deps]]
    name = "ModelingToolkitTearing"
    uuid = "6bb917b9-1269-42b9-9f7c-b0dca72083ab"
    [[Issues."11.0.0".deps]]
    name = "StateSelection"
    uuid = "64909d44-ed92-46a8-bbd9-f047dfbdc84b"

    [[Issues."11.0.0".weak_deps]]
    name = "FMI"
    uuid = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"
