[Status]
version = "1.5.0"

[[Issues."1.4.0"]]
version = "1.4.0"
type = "not_on_latest"
latest = "1.5.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqNordsieck"
uuid = "c9986a66-5c92-4813-8696-a7ec84c806c8"
