[Status]
version = "1.6.0"

[[Issues."1.5.0"]]
version = "1.5.0"
type = "not_on_latest"
latest = "1.6.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqHighOrderRK"
uuid = "d28bc4f8-55e1-4f49-af69-84c1a99f0f58"
