[Status]
version = "6.104.0"

[[Issues."6.103.0"]]
version = "6.103.0"
type = "not_on_latest"
latest = "6.104.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEq"
uuid = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
