[Pkg]
name = "OpenMPI_jll"
uuid = "fe0851c0-eecd-5654-98d4-656369965a5c"
is_jll = true

[Status]
version = "5.0.9+0"

[JLL.products]
executable = ["mpiexec"]
library = ["libmpi", "libmpi_mpifh", "libmpi_usempi_ignore_tkr", "libmpi_usempif08"]
