
[JLL.products]
library = ["libaws_c_http", "libaws_c_http_jq"]
[Status]
version = "0.10.10+0"

[[Issues."0.10.10+0"]]
type = "jll_changes"

    [Issues."0.10.10+0".add]
    library = ["libaws_c_http_jq"]

[Pkg]
is_jll = true
name = "aws_c_http_jll"
uuid = "3254fc65-9028-534d-aa9d-d76d128babc6"
