[Pkg]
name = "Symbolics"
uuid = "0c5d862f-8b57-4792-8d23-62f2024744c7"
required = true

[Status]
version = "6.57.0"

[[Issues."6.57.0"]]
type = "missing_deps"

    [[Issues."6.57.0".weak_deps]]
    name = "D3Trees"
    uuid = "e3df1716-f71e-5df9-9e2d-98e193103c45"
    [[Issues."6.57.0".weak_deps]]
    name = "Lux"
    uuid = "b2108857-7c20-44ae-9111-449ecde12c47"
    [[Issues."6.57.0".weak_deps]]
    name = "SymPy"
    uuid = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[[Issues."7.0.1"]]
type = "missing_deps"

    [[Issues."7.0.1".deps]]
    name = "AbstractPlutoDingetjes"
    uuid = "6e696c72-6542-2067-7265-42206c756150"

    [[Issues."7.0.1".weak_deps]]
    name = "D3Trees"
    uuid = "e3df1716-f71e-5df9-9e2d-98e193103c45"
    [[Issues."7.0.1".weak_deps]]
    name = "Lux"
    uuid = "b2108857-7c20-44ae-9111-449ecde12c47"
    [[Issues."7.0.1".weak_deps]]
    name = "SymPy"
    uuid = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[[Issues."7.0.0"]]
type = "missing_deps"

    [[Issues."7.0.0".deps]]
    name = "AbstractPlutoDingetjes"
    uuid = "6e696c72-6542-2067-7265-42206c756150"

    [[Issues."7.0.0".weak_deps]]
    name = "D3Trees"
    uuid = "e3df1716-f71e-5df9-9e2d-98e193103c45"
    [[Issues."7.0.0".weak_deps]]
    name = "Lux"
    uuid = "b2108857-7c20-44ae-9111-449ecde12c47"
    [[Issues."7.0.0".weak_deps]]
    name = "SymPy"
    uuid = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
