[Pkg]
name = "QECCore"
uuid = "b50d4dc9-2544-401f-bae9-a24ba40d0c7a"

[Status]
version = "0.1.2"

[[Issues."0.1.2"]]
type = "missing_deps"

    [[Issues."0.1.2".weak_deps]]
    name = "Oscar"
    uuid = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
