[Status]
version = "1.8.0"

[[Issues."1.7.0"]]
version = "1.7.0"
type = "not_on_latest"
latest = "1.8.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqLowStorageRK"
uuid = "b0944070-b475-4768-8dec-fb6eb410534d"
