[Pkg]
name = "HDF5_jll"
uuid = "0234f1f7-429e-5d53-9886-15a909be8d59"
is_jll = true

[Status]
version = "1.14.6+0"

[JLL.products]
executable = ["h5clear", "h5copy", "h5debug", "h5delete", "h5diff", "h5dump", "h5format_convert", "h5import", "h5jam", "h5ls", "h5mkgrp", "h5perf_serial", "h5repack", "h5repart", "h5stat", "h5unjam", "h5watch"]
library = ["libhdf5", "libhdf5_cpp", "libhdf5_fortran", "libhdf5_hl", "libhdf5_hl_cpp", "libhdf5_hl_fortran"]

[[Issues."1.14.6+0"]]
dependent = ["HDF5 [f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f]"]
dependency = ["aws_c_s3_jll [bd1f34fb-993f-5903-a121-aaf302eed6d4]"]
type = "not_on_latest"
version = "1.14.6+0"
latest = "2.0.0+2"
