[Pkg]
name = "OptimizationBase"
uuid = "bca83a33-5cc9-4baa-983d-23429ab6bcbb"

[Status]
version = "4.2.0"

[[Issues."4.2.0"]]
type = "missing_deps"

    [[Issues."4.2.0".weak_deps]]
    name = "MLDataDevices"
    uuid = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
    [[Issues."4.2.0".weak_deps]]
    name = "MLUtils"
    uuid = "f1d291b0-491e-4a28-83b9-f70985020b54"
