[Pkg]
name = "LineSearches"
uuid = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"

[Status]
version = "7.5.1"

[[Issues."7.5.1"]]
dependent = []
dependency = ["NLSolversBase [d41bc354-129a-5804-8e4c-c37616107c6c]"]
type = "not_on_latest"
version = "7.5.1"
latest = "7.6.0"
