[Pkg]
name = "Nemo"
uuid = "2edaba10-b0f1-5616-af89-8c11ac63239a"

[Status]
version = "0.52.4"

[[Issues."0.52.4"]]
dependent = ["Groebner [0b43b601-686d-58a3-8a1c-6623616c7cd4]"]
dependency = ["FLINT_jll [e134572f-a0d5-539d-bddf-3cad8db41a82]"]
type = "not_on_latest"
version = "0.52.4"
latest = "0.53.0"
