[Pkg]
name = "PreallocationTools"
uuid = "d236fae5-4411-538c-8e31-a6e3d9e00b46"

[Status]
version = "0.4.34"

[[Issues."0.4.34"]]
dependent = ["BoundaryValueDiffEqAscher [7227322d-7511-4e07-9247-ad6ff830280e]", "BoundaryValueDiffEqCore [56b672f2-a5fe-4263-ab2d-da677488eb3a]", "BoundaryValueDiffEqFIRK [85d9eb09-370e-4000-bb32-543851f73618]", "BoundaryValueDiffEqMIRK [1a22d4ce-7765-49ea-b6f2-13c8438986a6]", "BoundaryValueDiffEqMIRKN [9255f1d6-53bf-473e-b6bd-23f1ff009da4]", "BoundaryValueDiffEqShooting [ed55bfe0-3725-4db6-871e-a1dc9f42a757]", "LabelledArrays [2ee39098-c373-598a-b85f-a56591580800]", "ModelingToolkit [961ee093-0014-501f-94e3-6117800e7a78]", "OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]", "OrdinaryDiffEqNonlinearSolve [127b3ac7-2247-4354-8eb6-78cf4e7c58e8]", "SciMLBase [0bca4576-84f4-4d90-8ffe-ffa030f20462]"]
dependency = []
type = "not_on_latest"
version = "0.4.34"
latest = "1.0.0"
