[Pkg]
name = "FilePaths"
uuid = "8fc22ac5-c921-52a6-82fd-178b2807b824"

[Status]
version = "0.9.0"

[[Issues."0.9.0"]]
type = "missing_deps"

    [[Issues."0.9.0".weak_deps]]
    name = "URIParser"
    uuid = "30578b45-9adc-5946-b283-645ec420af67"
