[Pkg]
name = "SciMLBase"
uuid = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[Status]
version = "2.136.0"

[[Issues."2.136.0"]]
type = "missing_deps"

    [[Issues."2.136.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
    [[Issues."2.136.0".weak_deps]]
    name = "RCall"
    uuid = "6f49c342-dc21-5d91-9882-a32aef131414"
