[Status]
version = "1.10.0"

[[Issues."1.9.0"]]
version = "1.9.0"
type = "not_on_latest"
latest = "1.10.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqExtrapolation"
uuid = "becaefa8-8ca2-5cf9-886d-c06f3d2bd2c4"
