[Pkg]
name = "MathOptInterface"
uuid = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[Status]
version = "1.48.0"

[[Issues."1.48.0"]]
dependent = []
dependency = ["ForwardDiff [f6369f11-7733-5829-9624-2563aa707210]"]
type = "not_on_latest"
version = "1.48.0"
latest = "1.49.0"
