[Pkg]
name = "SuiteSparse32_jll"
uuid = "ca45d3f4-326b-53b0-9957-23b75aacb3f2"
is_jll = true

[Status]
version = "7.12.1+0"

[JLL.products]
library = ["libamd", "libbtf", "libcamd", "libccolamd", "libcholmod", "libcolamd", "libklu", "libldl", "librbio", "libspqr", "libsuitesparseconfig", "libumfpack"]
