[Status]
version = "8.0.0"

[[Issues."7.4.0"]]
version = "7.4.0"
type = "not_on_latest"
latest = "8.0.0"
dependent = ["LanguageServer [2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7]"]
dependency = []

[Pkg]
name = "SymbolServer"
uuid = "cf896787-08d5-524d-9de7-132aaa0cb996"
