[Status]
version = "0.4.8"

[[Issues."0.4.7"]]
version = "0.4.7"
type = "not_on_latest"
latest = "0.4.8"
dependent = ["Braket [19504a0f-b47d-4348-9127-acc6cc69ef67]"]
dependency = []

[Pkg]
name = "AxisArrays"
uuid = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
