[Pkg]
name = "NonlinearSolveBase"
uuid = "be0214bd-f91f-a760-ac4e-3421ce2b2da0"

[Status]
version = "2.5.0"

[[Issues."2.5.0"]]
type = "missing_deps"

    [[Issues."2.5.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
