[Pkg]
name = "Enzyme_jll"
uuid = "7cc45869-7501-5eee-bdea-0790c847d4ef"
is_jll = true

[Status]
version = "0.0.231+0"

[JLL.products]
library = ["libEnzyme", "libEnzymeBCLoad"]

[[Issues."0.0.231+0"]]
dependent = ["Enzyme [7da242da-08ed-463a-9acd-ee780be4f1d9]"]
dependency = []
type = "not_on_latest"
version = "0.0.231+0"
latest = "0.0.232+0"
