[Pkg]
name = "LoweredCodeUtils"
uuid = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"

[Status]
version = "3.4.2"

[[Issues."3.4.2"]]
dependent = []
dependency = ["CodeTracking [da1fd8a2-8d9e-5ec2-8556-3022fb5608a2]"]
type = "not_on_latest"
version = "3.4.2"
latest = "3.5.0"
