[Pkg]
name = "OrdinaryDiffEqFeagin"
uuid = "101fe9f7-ebb6-4678-b671-3a81e7194747"

[Status]
version = "1.7.0"

[[Issues."1.7.0"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]
type = "not_on_latest"
version = "1.7.0"
latest = "1.8.0"
