[Pkg]
name = "FLINT_jll"
uuid = "e134572f-a0d5-539d-bddf-3cad8db41a82"
is_jll = true

[Status]
version = "301.300.102+0"

[JLL.products]
library = ["libflint"]

[[Issues."301.300.102+0"]]
dependent = ["Nemo [2edaba10-b0f1-5616-af89-8c11ac63239a]"]
dependency = []
type = "not_on_latest"
version = "301.300.102+0"
latest = "301.400.1+0"
