[Pkg]
name = "MUMPS_seq_jll"
uuid = "d7ed1dd3-d0ae-5e8e-bfb4-87a502085b8d"
is_jll = true

[Status]
version = "500.800.200+0"

[JLL.products]
library = ["libcmumps", "libdmumps", "libsmumps", "libzmumps", "libcmumps64", "libdmumps64", "libsmumps64", "libzmumps64"]
