
[JLL.products]
library = ["libffi"]
[Status]
version = "3.5.2+0"

[[Issues."3.4.7+0"]]
version = "3.4.7+0"
type = "not_on_latest"
latest = "3.5.2+0"
dependent = ["Glib_jll [7746bdde-850d-59dc-9ae8-88ece973131d]", "HarfBuzz_jll [2e76f6c2-a576-52d4-95c1-20adfe4de566]", "Wayland_jll [a2964d1f-97da-50d4-b82a-358c7fce9d89]"]
dependency = []

[Pkg]
is_jll = true
name = "Libffi_jll"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
