[Status]
version = "0.9.12"

[[Issues."0.9.10"]]
version = "0.9.10"
type = "not_on_latest"
latest = "0.9.12"
dependent = []
dependency = ["LuxurySparse [d05aeea4-b7d4-55ac-b691-9e7fabb07ba2]"]

[Pkg]
name = "YaoArrayRegister"
uuid = "e600142f-9330-5003-8abb-0ebd767abc51"
