[Pkg]
name = "OrdinaryDiffEqSDIRK"
uuid = "2d112036-d095-4a1e-ab9a-08536f3ecdbf"

[Status]
version = "1.7.0"

[[Issues."1.7.0"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]
type = "not_on_latest"
version = "1.7.0"
latest = "1.10.0"
