[Pkg]
name = "OrdinaryDiffEqPDIRK"
uuid = "5dd0a6cf-3d4b-4314-aa06-06d4e299bc89"

[Status]
version = "1.9.0"

[[Issues."1.9.0"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]", "OrdinaryDiffEqDifferentiation [4302a76b-040a-498a-8c04-15b101fed76b]"]
type = "not_on_latest"
version = "1.9.0"
latest = "1.11.0"
