[Pkg]
name = "OrdinaryDiffEqSymplecticRK"
uuid = "fa646aed-7ef9-47eb-84c4-9443fc8cbfa8"

[Status]
version = "1.7.0"

[[Issues."1.7.0"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]
type = "not_on_latest"
version = "1.7.0"
latest = "1.9.0"
