[Pkg]
name = "JSON"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
required = true

[Status]
version = "0.21.4"

[[Issues."0.21.4"]]
dependent = ["AWS [fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc]", "BloqadeSchema [a64e8dd8-bb5a-11ec-104d-290571fc3a8d]", "GitHub [bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26]", "GitHubActions [6b79fd1a-b13a-48ab-b6b0-aaee1fee41df]", "JSONRPC [b9b8584e-8fd3-41f9-ad0c-7255d428e418]", "LanguageServer [2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7]", "OMEinsumContractionOrders [6f22d1fd-8eed-4bb7-9776-e7d684900715]"]
dependency = []
type = "not_on_latest"
version = "0.21.4"
latest = "1.2.1"
