[Pkg]
name = "Graphs"
uuid = "86223c79-3864-5bf0-83f7-82e725a168b6"

[Status]
version = "1.13.1"

[[Issues."1.13.1"]]
dependent = []
dependency = ["DataStructures [864edb3b-99cc-5e75-8d2d-829cb0a9cfe8]"]
type = "not_on_latest"
version = "1.13.1"
latest = "1.13.2"
