[Pkg]
name = "JuliaInterpreter"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"

[Status]
version = "0.10.3"

[[Issues."0.10.3"]]
dependent = []
dependency = ["CodeTracking [da1fd8a2-8d9e-5ec2-8556-3022fb5608a2]"]
type = "not_on_latest"
version = "0.10.3"
latest = "0.10.9"
