[Pkg]
name = "LibTracyClient_jll"
uuid = "ad6e5548-8b26-5c9f-8ef3-ef0ad883f3a5"
is_jll = true

[Status]
version = "0.13.1+0"

[JLL.products]
file = ["libTracyClient_static"]
library = ["libTracyClient"]
