[Pkg]
name = "FFMPEG_jll"
uuid = "b22a6f82-2f65-5046-a5b2-351ab43fb4e5"
is_jll = true

[Status]
version = "8.0.1+0"

[JLL.products]
executable = ["ffmpeg", "ffprobe"]
library = ["libavcodec", "libavdevice", "libavfilter", "libavformat", "libavutil", "libswresample", "libswscale"]
