[Status]
version = "1.7.0"

[[Issues."1.6.0"]]
version = "1.6.0"
type = "not_on_latest"
latest = "1.7.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqVerner"
uuid = "79d7bb75-1356-48c1-b8c0-6832512096c2"
