[Pkg]
name = "OrdinaryDiffEqDefault"
uuid = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"

[Status]
version = "1.11.0"

[[Issues."1.11.0"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]
type = "not_on_latest"
version = "1.11.0"
latest = "1.12.0"
