[Status]
version = "1.9.0"

[[Issues."1.8.0"]]
version = "1.8.0"
type = "not_on_latest"
latest = "1.9.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqDefault"
uuid = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
