[Status]
version = "2.2.0"

[[Issues."1.0.62"]]
version = "1.0.62"
type = "not_on_latest"
latest = "2.2.0"
dependent = ["LanguageServer [2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7]"]
dependency = ["JuliaSyntax [70703baa-626e-46a2-a12c-08ffd08c73b4]"]

[Pkg]
name = "JuliaFormatter"
uuid = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
