[Pkg]
name = "Revise"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"

[Status]
version = "3.7.4"

[[Issues."3.7.4"]]
dependent = []
dependency = ["CodeTracking [da1fd8a2-8d9e-5ec2-8556-3022fb5608a2]", "JuliaInterpreter [aa1ae85d-cabe-5617-a682-6adf51b2e16a]", "LoweredCodeUtils [6f1432cf-f94c-5a45-995e-cdbf5db27b0b]"]
type = "not_on_latest"
version = "3.7.4"
latest = "3.12.2"
