[Pkg]
name = "OrdinaryDiffEqStabilizedIRK"
uuid = "e3e12d00-db14-5390-b879-ac3dd2ef6296"

[Status]
version = "1.6.0"

[[Issues."1.6.0"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]
type = "not_on_latest"
version = "1.6.0"
latest = "1.9.0"
