[Pkg]
name = "OrdinaryDiffEqStabilizedIRK"
uuid = "e3e12d00-db14-5390-b879-ac3dd2ef6296"

[Status]
version = "1.6.0"

[[Issues."1.6.0"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]", "OrdinaryDiffEqDifferentiation [4302a76b-040a-498a-8c04-15b101fed76b]", "OrdinaryDiffEqNonlinearSolve [127b3ac7-2247-4354-8eb6-78cf4e7c58e8]"]
type = "not_on_latest"
version = "1.6.0"
latest = "1.11.0"
