[Pkg]
name = "ImplicitDiscreteSolve"
uuid = "3263718b-31ed-49cf-8a0f-35a466e8af96"

[Status]
version = "1.2.0"

[[Issues."1.2.0"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]
type = "not_on_latest"
version = "1.2.0"
latest = "1.7.0"
[[Issues."1.2.0"]]
type = "not_needed"
