[Status]
version = "1.3.0"

[[Issues."1.2.0"]]
version = "1.2.0"
type = "not_on_latest"
latest = "1.3.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]
[[Issues."1.2.0"]]
type = "not_needed"

[Pkg]
name = "ImplicitDiscreteSolve"
uuid = "3263718b-31ed-49cf-8a0f-35a466e8af96"
