[Status]
version = "0.9.6"

[[Issues."0.9.4"]]
version = "0.9.4"
type = "not_on_latest"
latest = "0.9.6"
dependent = []
dependency = ["YaoBlocks [418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df]"]

[Pkg]
name = "YaoPlots"
uuid = "32cfe2d9-419e-45f2-8191-2267705d8dbc"
