[Pkg]
name = "OrdinaryDiffEqCore"
uuid = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"

[Status]
version = "1.36.0"

[[Issues."1.36.0"]]
type = "missing_deps"

    [[Issues."1.36.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
[[Issues."1.36.0"]]
dependent = ["DelayDiffEq [bcd4f6db-9728-5f36-b5f7-82caef46ccdb]", "ImplicitDiscreteSolve [3263718b-31ed-49cf-8a0f-35a466e8af96]", "OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]", "OrdinaryDiffEqAdamsBashforthMoulton [89bda076-bce5-4f1c-845f-551c83cdda9a]", "OrdinaryDiffEqBDF [6ad6398a-0878-4a85-9266-38940aa047c8]", "OrdinaryDiffEqDefault [50262376-6c5a-4cf5-baba-aaf4f84d72d7]", "OrdinaryDiffEqDifferentiation [4302a76b-040a-498a-8c04-15b101fed76b]", "OrdinaryDiffEqExplicitRK [9286f039-9fbf-40e8-bf65-aa933bdc4db0]", "OrdinaryDiffEqExponentialRK [e0540318-69ee-4070-8777-9e2de6de23de]", "OrdinaryDiffEqExtrapolation [becaefa8-8ca2-5cf9-886d-c06f3d2bd2c4]", "OrdinaryDiffEqFIRK [5960d6e9-dd7a-4743-88e7-cf307b64f125]", "OrdinaryDiffEqFeagin [101fe9f7-ebb6-4678-b671-3a81e7194747]", "OrdinaryDiffEqFunctionMap [d3585ca7-f5d3-4ba6-8057-292ed1abd90f]", "OrdinaryDiffEqHighOrderRK [d28bc4f8-55e1-4f49-af69-84c1a99f0f58]", "OrdinaryDiffEqIMEXMultistep [9f002381-b378-40b7-97a6-27a27c83f129]", "OrdinaryDiffEqLinear [521117fe-8c41-49f8-b3b6-30780b3f0fb5]", "OrdinaryDiffEqLowOrderRK [1344f307-1e59-4825-a18e-ace9aa3fa4c6]", "OrdinaryDiffEqLowStorageRK [b0944070-b475-4768-8dec-fb6eb410534d]", "OrdinaryDiffEqNonlinearSolve [127b3ac7-2247-4354-8eb6-78cf4e7c58e8]", "OrdinaryDiffEqNordsieck [c9986a66-5c92-4813-8696-a7ec84c806c8]", "OrdinaryDiffEqPDIRK [5dd0a6cf-3d4b-4314-aa06-06d4e299bc89]", "OrdinaryDiffEqPRK [5b33eab2-c0f1-4480-b2c3-94bc1e80bda1]", "OrdinaryDiffEqQPRK [04162be5-8125-4266-98ed-640baecc6514]", "OrdinaryDiffEqRKN [af6ede74-add8-4cfd-b1df-9a4dbb109d7a]", "OrdinaryDiffEqRosenbrock [43230ef6-c299-4910-a778-202eb28ce4ce]", "OrdinaryDiffEqSDIRK [2d112036-d095-4a1e-ab9a-08536f3ecdbf]", "OrdinaryDiffEqSSPRK [669c94d9-1f4b-4b64-b377-1aa079aa2388]", "OrdinaryDiffEqStabilizedIRK [e3e12d00-db14-5390-b879-ac3dd2ef6296]", "OrdinaryDiffEqStabilizedRK [358294b1-0aab-51c3-aafe-ad5ab194a2ad]", "OrdinaryDiffEqSymplecticRK [fa646aed-7ef9-47eb-84c4-9443fc8cbfa8]", "OrdinaryDiffEqTsit5 [b1df2697-797e-41e3-8120-5422d3b24e4a]", "OrdinaryDiffEqVerner [79d7bb75-1356-48c1-b8c0-6832512096c2]", "QuantumOptics [6e0679c1-51ea-5a7c-ac74-d61b76210b0c]"]
dependency = []
type = "not_on_latest"
version = "1.36.0"
latest = "2.3.0"

[[Issues."2.3.0"]]
type = "missing_deps"

    [[Issues."2.3.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."2.0.0"]]
type = "missing_deps"

    [[Issues."2.0.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."2.2.0"]]
type = "missing_deps"

    [[Issues."2.2.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[[Issues."2.1.0"]]
type = "missing_deps"

    [[Issues."2.1.0".weak_deps]]
    name = "Mooncake"
    uuid = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
