[Status]
version = "0.6.3"

[[Issues."0.5.15"]]
version = "0.5.15"
type = "not_on_latest"
latest = "0.6.3"
dependent = ["Braket [19504a0f-b47d-4348-9127-acc6cc69ef67]"]
dependency = []

[Pkg]
name = "JLD2"
required = true
uuid = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
