[Status]
version = "0.10.2"

[[Issues."0.9.5"]]
version = "0.9.5"
type = "not_on_latest"
latest = "0.10.2"
dependent = ["YaoBlocks [418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df]"]
dependency = []

[Pkg]
name = "KrylovKit"
uuid = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
