[Status]
version = "0.2.4"

[[Issues."0.2.3"]]
version = "0.2.3"
type = "not_on_latest"
latest = "0.2.4"
dependent = []
dependency = ["SymbolicUtils [d1185830-fcd6-423d-90d6-eec64667417b]"]

[Pkg]
name = "SymbolicLimits"
uuid = "19f23fe9-fdab-4a78-91af-e7b7767979c3"
