[Pkg]
name = "DataStructures"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
required = true

[Status]
version = "0.18.22"

[[Issues."0.18.22"]]
dependent = ["ConcurrentSim [6ed1e86c-fcaf-46a9-97e0-2b26a2cdb499]", "ImageMorphology [787d08f9-d448-5407-9aad-5290dd7ab264]", "ImageSegmentation [80713f31-8817-5129-9cf8-209ff8fb23e1]", "JuliaFormatter [98e50ef6-434e-11e9-1051-2b60c6c9e899]", "Luxor [ae8d54c2-7ccd-5906-9d76-62fc9837b5bc]", "MultivariatePolynomials [102ac46a-7ee4-5c85-9060-abc95bfdeaa3]", "OMEinsumContractionOrders [6f22d1fd-8eed-4bb7-9776-e7d684900715]", "SymbolicAnalysis [4297ee4d-0239-47d8-ba5d-195ecdf594fe]"]
dependency = []
type = "not_on_latest"
version = "0.18.22"
latest = "0.19.3"
