[Pkg]
name = "OrdinaryDiffEqIMEXMultistep"
uuid = "9f002381-b378-40b7-97a6-27a27c83f129"

[Status]
version = "1.7.0"

[[Issues."1.7.0"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]", "OrdinaryDiffEqDifferentiation [4302a76b-040a-498a-8c04-15b101fed76b]", "OrdinaryDiffEqNonlinearSolve [127b3ac7-2247-4354-8eb6-78cf4e7c58e8]"]
type = "not_on_latest"
version = "1.7.0"
latest = "1.12.0"
