[Status]
version = "1.7.0"

[[Issues."1.6.0"]]
version = "1.6.0"
type = "not_on_latest"
latest = "1.7.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqLinear"
uuid = "521117fe-8c41-49f8-b3b6-30780b3f0fb5"
