[Pkg]
name = "Manifolds"
uuid = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"

[Status]
version = "0.10.23"

[[Issues."0.11.7"]]
type = "missing_deps"

    [[Issues."0.11.7".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.8"]]
type = "missing_deps"

    [[Issues."0.11.8".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.10.23"]]
type = "missing_deps"

    [[Issues."0.10.23".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.12"]]
type = "missing_deps"

    [[Issues."0.11.12".deps]]
    name = "Tullio"
    uuid = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[[Issues."0.11.10"]]
type = "missing_deps"

    [[Issues."0.11.10".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.9"]]
type = "missing_deps"

    [[Issues."0.11.9".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.11"]]
type = "missing_deps"

    [[Issues."0.11.11".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.0"]]
type = "missing_deps"

    [[Issues."0.11.0".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.3"]]
type = "missing_deps"

    [[Issues."0.11.3".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.4"]]
type = "missing_deps"

    [[Issues."0.11.4".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.2"]]
type = "missing_deps"

    [[Issues."0.11.2".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.5"]]
type = "missing_deps"

    [[Issues."0.11.5".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.1"]]
type = "missing_deps"

    [[Issues."0.11.1".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"

[[Issues."0.11.6"]]
type = "missing_deps"

    [[Issues."0.11.6".deps]]
    name = "Einsum"
    uuid = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
