[Pkg]
name = "Manifolds"
uuid = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"

[Status]
version = "0.10.23"

[[Issues."0.11.12"]]
type = "missing_deps"

    [[Issues."0.11.12".deps]]
    name = "Tullio"
    uuid = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
