[Status]
version = "1.19.0"

[[Issues."1.18.1"]]
version = "1.18.1"
type = "not_on_latest"
latest = "1.19.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqRosenbrock"
uuid = "43230ef6-c299-4910-a778-202eb28ce4ce"
