[Status]
version = "0.8.1"

[[Issues."0.7.9"]]
version = "0.7.9"
type = "not_on_latest"
latest = "0.8.1"
dependent = ["AWSS3 [1c724243-ef5b-51ab-93f4-b0a88ac62a95]"]
dependency = []

[Pkg]
name = "Mocking"
uuid = "78c3b35d-d492-501b-9361-3d52fe80e533"
