[Pkg]
name = "OrdinaryDiffEqNonlinearSolve"
uuid = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"

[Status]
version = "1.18.1"

[[Issues."1.18.1"]]
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]", "OrdinaryDiffEqDifferentiation [4302a76b-040a-498a-8c04-15b101fed76b]"]
type = "not_on_latest"
version = "1.18.1"
latest = "1.20.0"
