[Status]
version = "1.16.0"

[[Issues."1.15.0"]]
version = "1.15.0"
type = "not_on_latest"
latest = "1.16.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqNonlinearSolve"
uuid = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
