[Pkg]
name = "YaoToEinsum"
uuid = "9b173c7b-dc24-4dc5-a0e1-adab2f7b6ba9"

[Status]
version = "0.2.5"

[[Issues."0.2.5"]]
dependent = []
dependency = ["OMEinsum [ebe7aa44-baf0-506c-a96f-8464559b3922]", "YaoBlocks [418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df]"]
type = "not_on_latest"
version = "0.2.5"
latest = "0.2.9"
