[Status]
version = "1.17.0"

[[Issues."1.16.1"]]
version = "1.16.1"
type = "not_on_latest"
latest = "1.17.0"
dependent = []
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]

[Pkg]
name = "OrdinaryDiffEqDifferentiation"
uuid = "4302a76b-040a-498a-8c04-15b101fed76b"
