[Pkg]
name = "OrdinaryDiffEqDifferentiation"
uuid = "4302a76b-040a-498a-8c04-15b101fed76b"

[Status]
version = "1.21.0"

[[Issues."1.21.0"]]
dependent = ["DelayDiffEq [bcd4f6db-9728-5f36-b5f7-82caef46ccdb]", "OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]", "OrdinaryDiffEqBDF [6ad6398a-0878-4a85-9266-38940aa047c8]", "OrdinaryDiffEqExponentialRK [e0540318-69ee-4070-8777-9e2de6de23de]", "OrdinaryDiffEqExtrapolation [becaefa8-8ca2-5cf9-886d-c06f3d2bd2c4]", "OrdinaryDiffEqFIRK [5960d6e9-dd7a-4743-88e7-cf307b64f125]", "OrdinaryDiffEqIMEXMultistep [9f002381-b378-40b7-97a6-27a27c83f129]", "OrdinaryDiffEqNonlinearSolve [127b3ac7-2247-4354-8eb6-78cf4e7c58e8]", "OrdinaryDiffEqPDIRK [5dd0a6cf-3d4b-4314-aa06-06d4e299bc89]", "OrdinaryDiffEqRosenbrock [43230ef6-c299-4910-a778-202eb28ce4ce]", "OrdinaryDiffEqSDIRK [2d112036-d095-4a1e-ab9a-08536f3ecdbf]", "OrdinaryDiffEqStabilizedIRK [e3e12d00-db14-5390-b879-ac3dd2ef6296]", "StochasticDiffEq [789caeaf-c7a9-5a7d-9973-96adeb23e2a0]"]
dependency = ["OrdinaryDiffEqCore [bbf590c4-e513-4bbe-9b18-05decba2e5d8]"]
type = "not_on_latest"
version = "1.21.0"
latest = "2.0.0"
