[Pkg]
name = "VideoIO"
uuid = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"
required = true

[Status]
version = "1.3.2"

[[Issues."1.3.2"]]
dependent = []
dependency = ["FFMPEG_jll [b22a6f82-2f65-5046-a5b2-351ab43fb4e5]"]
type = "not_on_latest"
version = "1.3.2"
latest = "1.4.0"
