[Status]
version = "1.4.0"

[[Issues."1.3.2"]]
version = "1.3.2"
type = "not_on_latest"
latest = "1.4.0"
dependent = []
dependency = ["FFMPEG_jll [b22a6f82-2f65-5046-a5b2-351ab43fb4e5]"]

[Pkg]
name = "VideoIO"
required = true
uuid = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"
